[workspace]
resolver = "2"
members = [
    "crates/project-core",
    "crates/project-core/project-core-domain",
    "crates/project-rest-api",
]

[workspace.package]
authors = ["yallxe"]
license = "MIT"
readme = "README.md"
